repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: trailing-whitespace
  - repo: https://github.com/asottile/yesqa
    rev: v1.2.3
    hooks:
      - id: yesqa
  - repo: https://github.com/pycqa/isort
    rev: 5.4.0
    hooks:
      - id: isort
        name: Import Sorting
